# This file is a template, and might need editing before it works on your project.
# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
# This file assumes an own GitLab CI runner, setup on a macOS system.
stages:
  - build
  - test
  #- archive
  #- deploy

Compile & Build:
  stage: build
  script:
    - xcodebuild clean -project 'Fructus.xcodeproj' -scheme 'Fructus' # | xcpretty
  tags:
    - ios

Test on Small iPhone:
  stage: test
  script:
    - xcodebuild test -project 'Fructus.xcodeproj' -scheme 'Fructus' -destination 'platform=iOS Simulator,name=iPhone Small,OS=15.0' # | xcpretty -s
  tags:
    - ios

Test on Large iPhone:
  stage: test
  script:
    - xcodebuild test -project 'Fructus.xcodeproj' -scheme 'Fructus' -destination 'platform=iOS Simulator,name=iPhone Large,OS=15.0' # | xcpretty -s
  tags:
    - ios

Test on iPad:
  stage: test
  script:
    - xcodebuild test -project 'Fructus.xcodeproj' -scheme 'Fructus' -destination 'platform=iOS Simulator,name=iPad,OS=15.0' # | xcpretty -s
  tags:
    - ios

 # archive_project:
 # stage: archive
 # script:
 #   - xcodebuild clean archive -archivePath build/Fructus -scheme SchemeName
 #   - xcodebuild -exportArchive -exportFormat ipa -archivePath "build/Fructus.xcarchive" -exportPath "build/Fructus.ipa" -exportProvisioningProfile "ProvisioningProfileName"
 # only:
 #   - master
 # artifacts:
 #   paths:
 #     - build/Fructus.ipa
 # tags:
 #   - ios_11-3
 #   - xcode_9-3
 #   - macos_10-13 
